#CI de Nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execuçao Manual'

# regras de disparo (gatilho triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

    # trabalho/tarefas dentro do pipeline = jobs

jobs:
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos de scripts de build
    steps:
    # clone do projeto 
    - uses: actions/checkout@v4

    # instalacao do node
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    # instalacao do Yarn
    - name: Instalando Yarn
      run: yarn global add yarn

    # instalacao das dependencias
    - name: Instalando dependencias
      run: yarn

    # instalacao do Playwright
    - name: Instalando Playwright
      run: yarn playwright

    # executar os testes e2e
    - name: Executando Testes e2e
      run: yarn run e2e
