# CI de Nível 03 - Disparo apos a conclusao de um pipeline
# nome do nosso 'pipeline'

name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# Disparar o pipeline manualmente
# gatilho de execução manual = workflow_dispatch
# gatilho de exec a partir de outro pipe = workflow_run


on:
  workflow_run:
    workflows: [ 'Execução Manual' ] # jobs = tarefas que serão executadas
    types:
    - completed

jobs:
  # nome do job
  e2e-tests:
    # condicional - if
    # `${ expressao}´
    # == comparação de igualdade

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
    # clone do projeto
    - uses: actions/checkout@v4

    # instalação do node
    - uses: actions/checkout@v4
      with:
        node-version: 22.x

    # instalação do yarn
    - name: Instalando Yarn
      run: npm install -g yarn

    # instalação das dependências do projeto
    - name: Instalando dependências do projeto
      run: yarn

    # setup playwright
    - name: Instalando Playwright
      run: yarn playwright install

    # execução dos testes
    - name: Executando Testes E2E
      run: yarn run e2e
    - uses: actions/upload-artifact@v4
      if: ${{!cacelled()}}
      with:
        name: relatorio
        path: ./playwright-report
